name: intro_to_pytorch
channels:
  - defaults
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - ipympl
  - jupyter
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pickleshare
  - pillow
  - pip>=20.3.1
  - python>=3.7.9
  - pytorch
  - torchvision
  - seaborn
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
