name: intro_to_pytorch
channels:
  - defaults
dependencies:
  - _pytorch_select=0.1
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - notebook=6.1.4
  - numpy=1.19.2
  - pandas=1.1.3
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.1
  - python=3.7.9
  - pytorch=1.3.1
  - torchvision=0.4.2
